### ISSUE TITLE
Spell wrong number format

### ISSUE THREAD

**Issue by Ram4GB** [tonghoangvu/read-vietnamese-number#33]
When I typed `000100.01` or `000100.10`. There is no different between these cases. 

<img width="990" alt="CleanShot 2023-10-24 at 08 34 26@2x" src="https://github.com/tonghoangvu/read-vietnamese-number/assets/43853507/bae9e7a1-7e5a-427e-84cd-bdf4bfc50e63">
<img width="990" alt="CleanShot 2023-10-24 at 08 34 38@2x" src="https://github.com/tonghoangvu/read-vietnamese-number/assets/43853507/c2670f4d-0719-4799-84ec-b616c8b244da">

**Comment by tonghoangvu** [comment]
@Ram4GB Thanks for reporting the issue. I'm trying to fix it as soon as possible.

**Comment by tonghoangvu** [comment]
Temporarily fixed in 2.1.3. We're planning to refactor the core algorithm in the next v3 release, which has better tests as well.
