### ISSUE TITLE
Issue JSON on ubuntu

### ISSUE THREAD

**Issue by TranNghiaHiep** [tonghoangvu/read-vietnamese-number#36]
pakcage: "read-vietnamese-number"
version: 2.1.4 (latest)

Run start with error:
node_modules/read-vietnamese-number/dist/cjs/package.json: Expected property name or '}' in JSON at position 1

**Comment by tonghoangvu** [comment]
Hi @TranNghiaHiep,

Thank you for reporting the issue. Could you provide the content of the `node_modules/read-vietnamese-number/dist/cjs/package.json` file? This will help me in bug troubleshooting.

I also noticed you opened a PR; it looks good to me.

**Comment by TranNghiaHiep** [comment]
Content of the node_modules/read-vietnamese-number/dist/cjs/package.json file:
{type: commonjs}

==> Error: node_modules/read-vietnamese-number/dist/cjs/package.json: Expected property name or '}' in JSON at position 1

Updated:
{"type": "commonjs"}
==> It works fine now. The issue only occurs on Ubuntu; it works without any problem on my Mac.

**Comment by tonghoangvu** [comment]
Looks like the root cause is the `build` script producing invalid JSON format. I've checked the package on NPM, the issue only happens on v2.1.4 (latest).
